celestial:
  version: v1
  address: localhost:8000
  db:
      - 0.0.0.0:2379
  client:
    security:
      cert: path/to/file/
      key: path/to/file/
      trusted: path/to/file/
  dialtimeout: 5
  requesttimeout: 10
