celestial:
  version: v1
  client:
    security:
      cert: path/to/file/
      key: path/to/file/
      trusted: path/to/file/
    endpoints:
      - 0.0.0.0:2379
    dialtimeout: 5
    requesttimeout: 10
  connection:
    rpc:
      address: localhost:8000
    rest:
      address: localhost:8000
    standalone: True
