celestial:
  endpoints:
    - localhost1:8000
    - localhost2:8000
    - localhost3:8000
  dialtimeout: 2
  requesttimeout: 10

# celestial:
#   client:
#     security:
#       cert: path/to/file/
#       key: path/to/file/
#       trusted: path/to/file/
#     endpoints:
#       - localhost1:8000
#       - localhost2:8000
#       - localhost3:8000
#     dialtimeout: 2
#     requesttimeout: 10
#   connection:
#     rpc:
#       address: localhost:8000
#     rest:
#       address: localhost:8000
#     standalone: True
